apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: nexadesk
  labels:
    app.kubernetes.io/name: nexadesk
    app.kubernetes.io/component: backend
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: nexadesk
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8000
      targetPort: http
