/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health/live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness Probe
     * @description Report process liveness for container probes.
     *
     *     Returns:
     *         dict: static status payload confirming the process is running.
     */
    get: operations['liveness_probe_health_live_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness Probe
     * @description Check backing services and report readiness.
     *
     *     Pings PostgreSQL and Redis in parallel with a short timeout; any
     *     failure downgrades the result to an error state.
     *
     *     Args:
     *         request: incoming request used to reach the application state.
     *
     *     Returns:
     *         JSONResponse: per-service status with HTTP 200 when everything is
     *         healthy and HTTP 503 otherwise.
     */
    get: operations['readiness_probe_health_ready_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register
     * @description Register a new user account.
     *
     *     Args:
     *         request: incoming request, kept for the rate limiter.
     *         user: registration payload with email, name and password.
     *         session: active database session.
     *         service: user domain service.
     *
     *     Returns:
     *         UserRead: the created user.
     */
    post: operations['register_api_v1_register_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login
     * @description Authenticate a user and issue a token pair.
     *
     *     Args:
     *         request: incoming request, kept for the rate limiter.
     *         response: response used to set the refresh token cookie.
     *         form_data: OAuth2 form with username (email) and password.
     *         session: active database session.
     *         redis_client: redis client storing refresh tokens.
     *         service: auth domain service.
     *
     *     Returns:
     *         Token: the issued access token.
     */
    post: operations['login_api_v1_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh
     * @description Rotate the refresh token and issue a new access token.
     *
     *     Args:
     *         request: incoming request carrying the refresh token cookie.
     *         response: response used to set the rotated refresh token cookie.
     *         session: active database session.
     *         redis_client: redis client storing refresh tokens.
     *         service: auth domain service.
     *
     *     Returns:
     *         Token: the newly issued access token.
     */
    post: operations['refresh_api_v1_refresh_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout
     * @description Revoke the refresh token and clear the auth cookie.
     *
     *     Errors from an invalid or expired token are ignored: the session
     *     is considered over either way.
     *
     *     Args:
     *         request: incoming request carrying the refresh token cookie.
     *         response: response used to delete the refresh token cookie.
     *         session: active database session.
     *         redis_client: redis client storing refresh tokens.
     *         service: auth domain service.
     *
     *     Returns:
     *         dict: confirmation message.
     */
    post: operations['logout_api_v1_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/about_me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** About */
    get: operations['about_api_v1_about_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Projects
     * @description Get projects available to the current user.
     *
     *     Args:
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: project domain service.
     *         page: pagination parameters.
     *         search: optional substring filter on key and name.
     *         archived: archive filter, archived projects are excluded by default.
     *         sort: sort key from the collection whitelist.
     *
     *     Returns:
     *         Paginated[ProjectListItem]: one page of projects with caller roles.
     */
    get: operations['list_projects_api_v1_projects_get'];
    put?: never;
    /**
     * Create Project
     * @description Create a project owned by the current user.
     *
     *     Args:
     *         data: validated project creation payload.
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: project domain service.
     *
     *     Returns:
     *         ProjectCreated: the created project.
     */
    post: operations['create_project_api_v1_projects_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects/{project_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Project
     * @description Get project details.
     *
     *     Args:
     *         current_user: authenticated project member.
     *         session: active database session.
     *         service: project domain service.
     *         project_id: project to read.
     *
     *     Returns:
     *         ProjectRead: project details with counters.
     */
    get: operations['get_project_api_v1_projects__project_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update Project
     * @description Update project metadata.
     *
     *     Args:
     *         data: merge patch payload with editable fields.
     *         current_user: authenticated project owner or admin.
     *         session: active database session.
     *         service: project domain service.
     *         project_id: project to update.
     *
     *     Returns:
     *         ProjectRead: the updated project details.
     */
    patch: operations['update_project_api_v1_projects__project_id__patch'];
    trace?: never;
  };
  '/api/v1/projects/{project_id}/archive': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Archive Project
     * @description Archive a project and freeze all domain writes.
     *
     *     Args:
     *         current_user: authenticated project owner or admin.
     *         session: active database session.
     *         service: project domain service.
     *         project_id: project to archive.
     *
     *     Returns:
     *         ProjectRead: the archived project details.
     */
    post: operations['archive_project_api_v1_projects__project_id__archive_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects/{project_id}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Restore Project
     * @description Restore an archived project.
     *
     *     Args:
     *         current_user: authenticated project owner or admin.
     *         session: active database session.
     *         service: project domain service.
     *         project_id: project to restore.
     *
     *     Returns:
     *         ProjectRead: the restored project details.
     */
    post: operations['restore_project_api_v1_projects__project_id__restore_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects/{project_id}/transfer-ownership': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Transfer Ownership
     * @description Transfer project ownership to another member.
     *
     *     Args:
     *         data: command payload naming the new owner.
     *         current_user: authenticated project owner.
     *         session: active database session.
     *         service: project domain service.
     *         project_id: project whose ownership is transferred.
     *
     *     Returns:
     *         ProjectRead: the project details with the new owner.
     */
    post: operations['transfer_ownership_api_v1_projects__project_id__transfer_ownership_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects/{project_id}/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Members
     * @description List project members.
     *
     *     Args:
     *         current_user: authenticated project member.
     *         session: active database session.
     *         service: project domain service.
     *         project_id: project to inspect.
     *
     *     Returns:
     *         MemberList: membership rows ordered by user id.
     */
    get: operations['list_members_api_v1_projects__project_id__members_get'];
    put?: never;
    /**
     * Add Member
     * @description Add an existing user to a project.
     *
     *     Args:
     *         data: command payload with the user and his role.
     *         current_user: authenticated project owner or admin.
     *         session: active database session.
     *         service: project domain service.
     *         project_id: project to extend.
     *
     *     Returns:
     *         MemberRead: the created membership.
     */
    post: operations['add_member_api_v1_projects__project_id__members_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects/{project_id}/members/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Remove Member
     * @description Remove a project member.
     *
     *     Args:
     *         current_user: authenticated project owner or admin.
     *         session: active database session.
     *         service: project domain service.
     *         project_id: project to manage.
     *         user_id: member to remove.
     *
     *     Returns:
     *         None: the response carries no body.
     */
    delete: operations['remove_member_api_v1_projects__project_id__members__user_id__delete'];
    options?: never;
    head?: never;
    /**
     * Change Member Role
     * @description Change a project member role.
     *
     *     Args:
     *         data: command payload with the new role.
     *         current_user: authenticated project owner or admin.
     *         session: active database session.
     *         service: project domain service.
     *         project_id: project to manage.
     *         user_id: member whose role changes.
     *
     *     Returns:
     *         MemberRead: the updated membership.
     */
    patch: operations['change_member_role_api_v1_projects__project_id__members__user_id__patch'];
    trace?: never;
  };
  '/api/v1/projects/{project_id}/statuses': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Statuses
     * @description List project task statuses.
     *
     *     Args:
     *         current_user: authenticated project member.
     *         session: active database session.
     *         service: board status domain service.
     *         project_id: project to inspect.
     *
     *     Returns:
     *         list[TaskStatusRead]: statuses in board order.
     */
    get: operations['list_statuses_api_v1_projects__project_id__statuses_get'];
    put?: never;
    /**
     * Create Status
     * @description Create a custom board status.
     *
     *     Args:
     *         data: validated status creation payload.
     *         current_user: authenticated project owner or admin.
     *         session: active database session.
     *         service: board status domain service.
     *         project_id: project to extend.
     *
     *     Returns:
     *         TaskStatusRead: the created status.
     */
    post: operations['create_status_api_v1_projects__project_id__statuses_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects/{project_id}/statuses/{status_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Status
     * @description Delete a board status that holds no tasks.
     *
     *     Args:
     *         current_user: authenticated project owner or admin.
     *         session: active database session.
     *         service: board status domain service.
     *         project_id: project owning the status.
     *         status_id: status to delete.
     *
     *     Returns:
     *         None: the response carries no body.
     */
    delete: operations['delete_status_api_v1_projects__project_id__statuses__status_id__delete'];
    options?: never;
    head?: never;
    /**
     * Update Status
     * @description Update status metadata or board position.
     *
     *     Args:
     *         data: merge patch payload with editable fields.
     *         current_user: authenticated project owner or admin.
     *         session: active database session.
     *         service: board status domain service.
     *         project_id: project owning the status.
     *         status_id: status to update.
     *
     *     Returns:
     *         TaskStatusRead: the updated status.
     */
    patch: operations['update_status_api_v1_projects__project_id__statuses__status_id__patch'];
    trace?: never;
  };
  '/api/v1/projects/{project_id}/tasks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Tasks
     * @description List and filter project tasks.
     *
     *     Args:
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: task domain service.
     *         project_id: project to inspect.
     *         page: pagination parameters.
     *         search: substring filter on title and description.
     *         status_key: status key filter.
     *         priority: priority filter.
     *         assignee_id: assignee filter.
     *         creator_id: creator filter.
     *         due_before: due date upper bound.
     *         due_after: due date lower bound.
     *         sort: sort key from the collection whitelist.
     *
     *     Returns:
     *         Paginated[TaskListItem]: one page of task cards.
     */
    get: operations['list_tasks_api_v1_projects__project_id__tasks_get'];
    put?: never;
    /**
     * Create Task
     * @description Create a task in a project.
     *
     *     Args:
     *         data: validated task creation payload.
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: task domain service.
     *         project_id: project to extend.
     *
     *     Returns:
     *         TaskRead: the created task.
     */
    post: operations['create_task_api_v1_projects__project_id__tasks_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects/{project_id}/board': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Board
     * @description Return tasks grouped by board column.
     *
     *     Args:
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: task domain service.
     *         project_id: project to render.
     *         limit_per_column: maximum number of cards per column.
     *
     *     Returns:
     *         BoardRead: board columns with cards and has_more flags.
     */
    get: operations['get_board_api_v1_projects__project_id__board_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tasks/{task_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Task
     * @description Get a single task.
     *
     *     Args:
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: task domain service.
     *         task_id: task to read.
     *
     *     Returns:
     *         TaskRead: the task with its current version.
     */
    get: operations['get_task_api_v1_tasks__task_id__get'];
    put?: never;
    post?: never;
    /**
     * Delete Task
     * @description Soft-delete a task.
     *
     *     Args:
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: task domain service.
     *         version: task version from the If-Match header.
     *         task_id: task to delete.
     *
     *     Returns:
     *         None: the response carries no body.
     */
    delete: operations['delete_task_api_v1_tasks__task_id__delete'];
    options?: never;
    head?: never;
    /**
     * Update Task
     * @description Update editable task fields.
     *
     *     Args:
     *         data: merge patch payload with editable fields.
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: task domain service.
     *         version: task version from the If-Match header.
     *         task_id: task to update.
     *
     *     Returns:
     *         TaskRead: the updated task.
     */
    patch: operations['update_task_api_v1_tasks__task_id__patch'];
    trace?: never;
  };
  '/api/v1/tasks/{task_id}/transition': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Transition Task
     * @description Move a task to an adjacent board column.
     *
     *     Args:
     *         data: command payload naming the target status.
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: task domain service.
     *         task_id: task to move.
     *
     *     Returns:
     *         TaskTransitionRead: the task with its new status.
     */
    post: operations['transition_task_api_v1_tasks__task_id__transition_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tasks/{task_id}/assign': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Assign Task
     * @description Assign a task to a project member.
     *
     *     Args:
     *         data: command payload naming the assignee.
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: task domain service.
     *         task_id: task to modify.
     *
     *     Returns:
     *         TaskAssignRead: the task with its new assignee.
     */
    post: operations['assign_task_api_v1_tasks__task_id__assign_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tasks/{task_id}/unassign': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Unassign Task
     * @description Remove the current assignee of a task.
     *
     *     Args:
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: task domain service.
     *         task_id: task to modify.
     *
     *     Returns:
     *         TaskAssignRead: the task without an assignee.
     */
    post: operations['unassign_task_api_v1_tasks__task_id__unassign_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tasks/{task_id}/reorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reorder Task
     * @description Place a card inside a board column and recalculate ranks.
     *
     *     Args:
     *         data: command payload with the target column and neighbors.
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: task domain service.
     *         task_id: card to move.
     *
     *     Returns:
     *         TaskPositionRead: the final position of the card.
     */
    post: operations['reorder_task_api_v1_tasks__task_id__reorder_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects/{project_id}/activity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Project Activity
     * @description List project activity history, newest first.
     *
     *     Args:
     *         page: pagination parameters.
     *         current_user: authenticated project member.
     *         session: active database session.
     *         service: activity history query service.
     *         project_id: project to inspect.
     *
     *     Returns:
     *         Paginated[ActivityEventRead]: one page of history entries.
     */
    get: operations['list_project_activity_api_v1_projects__project_id__activity_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tasks/{task_id}/activity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Task Activity
     * @description List activity history of a single task, newest first.
     *
     *     Args:
     *         page: pagination parameters.
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: activity history query service.
     *         task_id: task to inspect.
     *
     *     Returns:
     *         Paginated[ActivityEventRead]: one page of history entries.
     */
    get: operations['list_task_activity_api_v1_tasks__task_id__activity_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects/{project_id}/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Project realtime event stream (SSE)
     * @description Open a server-sent events stream of one project.
     *
     *     The caller must be a project member. Events missed since the last seen
     *     id are replayed first when the client reconnects with the
     *     ``Last-Event-ID`` header, then live events follow, interleaved with
     *     heartbeat comments.
     *
     *     Args:
     *         request: incoming request carrying the Last-Event-ID header.
     *         current_user: authenticated project member.
     *         session: database session used for replay lookups.
     *         manager: registry of open streams per client and project.
     *         activity_crud: activity history storage.
     *         redis_client: broker delivering live project events.
     *         settings: application settings with stream limits.
     *         project_id: project to stream.
     *
     *     Returns:
     *         EventSourceResponse: stream of SSE frames.
     */
    get: operations['project_events_api_v1_projects__project_id__events_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tasks/{task_id}/comments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Comments
     * @description List live comments of a task, oldest first.
     *
     *     Args:
     *         page: pagination parameters.
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: comment domain service.
     *         task_id: task to inspect.
     *
     *     Returns:
     *         Paginated[CommentRead]: one page of comments.
     */
    get: operations['list_comments_api_v1_tasks__task_id__comments_get'];
    put?: never;
    /**
     * Create Comment
     * @description Create a comment on a task.
     *
     *     Args:
     *         data: validated comment creation payload.
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: comment domain service.
     *         task_id: task to comment on.
     *
     *     Returns:
     *         CommentRead: the created comment.
     */
    post: operations['create_comment_api_v1_tasks__task_id__comments_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/comments/{comment_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Comment
     * @description Soft-delete a comment, keeping the activity history.
     *
     *     Args:
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: comment domain service.
     *         comment_id: comment to hide.
     *
     *     Returns:
     *         None: the response carries no body.
     */
    delete: operations['delete_comment_api_v1_comments__comment_id__delete'];
    options?: never;
    head?: never;
    /**
     * Update Comment
     * @description Update the body of a comment.
     *
     *     Args:
     *         data: merge patch payload with editable fields.
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: comment domain service.
     *         comment_id: comment to update.
     *
     *     Returns:
     *         CommentRead: the updated comment.
     */
    patch: operations['update_comment_api_v1_comments__comment_id__patch'];
    trace?: never;
  };
  '/api/v1/projects/{project_id}/labels': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Labels
     * @description List project labels.
     *
     *     Args:
     *         current_user: authenticated project member.
     *         session: active database session.
     *         service: label domain service.
     *         project_id: project to inspect.
     *
     *     Returns:
     *         list[LabelRead]: labels of the project ordered by name.
     */
    get: operations['list_labels_api_v1_projects__project_id__labels_get'];
    put?: never;
    /**
     * Create Label
     * @description Create a project label.
     *
     *     Args:
     *         data: validated label creation payload.
     *         current_user: authenticated project owner or admin.
     *         session: active database session.
     *         service: label domain service.
     *         project_id: project to extend.
     *
     *     Returns:
     *         LabelRead: the created label.
     */
    post: operations['create_label_api_v1_projects__project_id__labels_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects/{project_id}/labels/{label_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Label
     * @description Delete a label and detach it from every task.
     *
     *     Args:
     *         current_user: authenticated project owner or admin.
     *         session: active database session.
     *         service: label domain service.
     *         project_id: project owning the label.
     *         label_id: label to delete.
     *
     *     Returns:
     *         None: the response carries no body.
     */
    delete: operations['delete_label_api_v1_projects__project_id__labels__label_id__delete'];
    options?: never;
    head?: never;
    /**
     * Update Label
     * @description Update label metadata.
     *
     *     Args:
     *         data: merge patch payload with editable fields.
     *         current_user: authenticated project owner or admin.
     *         session: active database session.
     *         service: label domain service.
     *         project_id: project owning the label.
     *         label_id: label to update.
     *
     *     Returns:
     *         LabelRead: the updated label.
     */
    patch: operations['update_label_api_v1_projects__project_id__labels__label_id__patch'];
    trace?: never;
  };
  '/api/v1/tasks/{task_id}/labels/{label_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Attach Label
     * @description Attach a project label to a task.
     *
     *     Args:
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: label domain service.
     *         task_id: task to extend.
     *         label_id: label to attach.
     *
     *     Returns:
     *         LabelRead: the attached label.
     */
    post: operations['attach_label_api_v1_tasks__task_id__labels__label_id__post'];
    /**
     * Detach Label
     * @description Remove a label from a task.
     *
     *     Args:
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: label domain service.
     *         task_id: task to update.
     *         label_id: label to remove.
     *
     *     Returns:
     *         None: the response carries no body.
     */
    delete: operations['detach_label_api_v1_tasks__task_id__labels__label_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tasks/{task_id}/watchers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Watchers
     * @description List the watchers of a task.
     *
     *     Args:
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: watcher domain service.
     *         task_id: task to inspect.
     *
     *     Returns:
     *         list[WatcherRead]: watcher subscriptions.
     */
    get: operations['list_watchers_api_v1_tasks__task_id__watchers_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tasks/{task_id}/watch': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Watch Task
     * @description Subscribe the caller to task changes.
     *
     *     Args:
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: watcher domain service.
     *         task_id: task to watch.
     *
     *     Returns:
     *         WatcherRead: the caller subscription.
     */
    post: operations['watch_task_api_v1_tasks__task_id__watch_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tasks/{task_id}/unwatch': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Unwatch Task
     * @description Unsubscribe the caller from task changes.
     *
     *     Args:
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: watcher domain service.
     *         task_id: task to stop watching.
     *
     *     Returns:
     *         None: the response carries no body.
     */
    post: operations['unwatch_task_api_v1_tasks__task_id__unwatch_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tasks/{task_id}/watchers/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Remove Watcher
     * @description Remove one watcher from a task.
     *
     *     Args:
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: watcher domain service.
     *         task_id: task to update.
     *         user_id: watcher to remove.
     *
     *     Returns:
     *         None: the response carries no body.
     */
    delete: operations['remove_watcher_api_v1_tasks__task_id__watchers__user_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/notifications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Notifications
     * @description List notifications of the current user, newest first.
     *
     *     Args:
     *         page: pagination parameters.
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: notification domain service.
     *         read: False returns only unread notifications, True only read
     *             ones, omitted returns everything.
     *
     *     Returns:
     *         Paginated[NotificationRead]: one page of notifications.
     */
    get: operations['list_notifications_api_v1_notifications_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/notifications/{notification_id}/read': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mark Notification Read
     * @description Mark one notification of the current user as read.
     *
     *     Marking an already read notification is a no-op.
     *
     *     Args:
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: notification domain service.
     *         notification_id: notification to mark.
     *
     *     Returns:
     *         NotificationRead: the updated notification.
     */
    post: operations['mark_notification_read_api_v1_notifications__notification_id__read_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/notifications/read-all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mark All Notifications Read
     * @description Mark every unread notification of the current user as read.
     *
     *     Args:
     *         current_user: authenticated caller.
     *         session: active database session.
     *         service: notification domain service.
     *
     *     Returns:
     *         None: the response carries no body.
     */
    post: operations['mark_all_notifications_read_api_v1_notifications_read_all_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ActivityEventRead */
    ActivityEventRead: {
      /** Id */
      id: string;
      type: components['schemas']['ActivityEventType'];
      actor?: components['schemas']['UserBrief'] | null;
      /** Task Id */
      task_id?: number | null;
      /** Data */
      data: {
        [key: string]: unknown;
      };
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * ActivityEventType
     * @description Type key of an immutable activity history entry.
     * @enum {string}
     */
    ActivityEventType:
      | 'project.created'
      | 'project.updated'
      | 'project.archived'
      | 'project.restored'
      | 'member.added'
      | 'member.removed'
      | 'member.role_changed'
      | 'task.created'
      | 'task.updated'
      | 'task.deleted'
      | 'task.assigned'
      | 'task.unassigned'
      | 'task.status_changed'
      | 'task.moved'
      | 'relation.added'
      | 'relation.removed'
      | 'watcher.added'
      | 'watcher.removed'
      | 'comment.created'
      | 'comment.updated'
      | 'comment.deleted'
      | 'comment.mentioned'
      | 'label.added'
      | 'label.removed';
    /** BoardCard */
    BoardCard: {
      /** Id */
      id: number;
      /** Key */
      key: string;
      /** Title */
      title: string;
      priority: components['schemas']['Priority'];
      assignee?: components['schemas']['UserBrief'] | null;
      /** Rank */
      rank: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** BoardColumn */
    BoardColumn: {
      status: components['schemas']['TaskStatusRead'];
      /** Tasks */
      tasks: components['schemas']['BoardCard'][];
      /** Has More */
      has_more: boolean;
    };
    /** BoardRead */
    BoardRead: {
      /** Columns */
      columns: components['schemas']['BoardColumn'][];
    };
    /** Body_login_api_v1_login_post */
    Body_login_api_v1_login_post: {
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /**
       * Password
       * Format: password
       */
      password: string;
      /**
       * Scope
       * @default
       */
      scope: string;
      /** Client Id */
      client_id?: string | null;
      /**
       * Client Secret
       * Format: password
       */
      client_secret?: string | null;
    };
    /** CommentCreate */
    CommentCreate: {
      /** Body */
      body: string;
    };
    /** CommentPatch */
    CommentPatch: {
      /** Body */
      body?: string | null;
    };
    /** CommentRead */
    CommentRead: {
      /** Id */
      id: number;
      /** Task Id */
      task_id: number;
      author: components['schemas']['UserBrief'];
      /** Body */
      body: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** LabelCreate */
    LabelCreate: {
      /** Name */
      name: string;
      /** Color */
      color: string;
    };
    /** LabelPatch */
    LabelPatch: {
      /** Name */
      name?: string | null;
      /** Color */
      color?: string | null;
    };
    /** LabelRead */
    LabelRead: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Color */
      color: string;
    };
    /** MemberAdd */
    MemberAdd: {
      /** User Id */
      user_id: number;
      /** @default member */
      role: components['schemas']['ProjectRole'];
    };
    /** MemberList */
    MemberList: {
      /** Items */
      items: components['schemas']['MemberRead'][];
    };
    /** MemberRead */
    MemberRead: {
      user: components['schemas']['UserBrief'];
      role: components['schemas']['ProjectRole'];
      /**
       * Joined At
       * Format: date-time
       */
      joined_at: string;
    };
    /** MemberRolePatch */
    MemberRolePatch: {
      role: components['schemas']['ProjectRole'];
    };
    /** NotificationProject */
    NotificationProject: {
      /** Id */
      id: number;
      /** Key */
      key: string;
    };
    /** NotificationRead */
    NotificationRead: {
      /** Id */
      id: number;
      type: components['schemas']['NotificationType'];
      project?: components['schemas']['NotificationProject'] | null;
      task?: components['schemas']['NotificationTask'] | null;
      actor?: components['schemas']['UserBrief'] | null;
      /** Data */
      data?: {
        [key: string]: unknown;
      };
      /** Is Read */
      is_read: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** NotificationTask */
    NotificationTask: {
      /** Id */
      id: number;
      /** Key */
      key: string;
      /** Title */
      title: string;
    };
    /**
     * NotificationType
     * @description Reason a notification was created for its recipient.
     * @enum {string}
     */
    NotificationType:
      | 'task.assigned'
      | 'comment.created'
      | 'comment.mentioned'
      | 'task.status_changed'
      | 'task.updated'
      | 'member.added';
    /** OwnershipTransfer */
    OwnershipTransfer: {
      /** User Id */
      user_id: number;
    };
    /** Paginated[ActivityEventRead] */
    Paginated_ActivityEventRead_: {
      /** Items */
      items: components['schemas']['ActivityEventRead'][];
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total */
      total: number;
    };
    /** Paginated[CommentRead] */
    Paginated_CommentRead_: {
      /** Items */
      items: components['schemas']['CommentRead'][];
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total */
      total: number;
    };
    /** Paginated[NotificationRead] */
    Paginated_NotificationRead_: {
      /** Items */
      items: components['schemas']['NotificationRead'][];
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total */
      total: number;
    };
    /** Paginated[ProjectListItem] */
    Paginated_ProjectListItem_: {
      /** Items */
      items: components['schemas']['ProjectListItem'][];
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total */
      total: number;
    };
    /** Paginated[TaskListItem] */
    Paginated_TaskListItem_: {
      /** Items */
      items: components['schemas']['TaskListItem'][];
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total */
      total: number;
    };
    /**
     * Priority
     * @description Task priority accepted by task create and patch payloads.
     * @enum {string}
     */
    Priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
    /** ProjectCreate */
    ProjectCreate: {
      /** Key */
      key: string;
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
    };
    /** ProjectCreated */
    ProjectCreated: {
      /** Id */
      id: number;
      /** Key */
      key: string;
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /** Owner Id */
      owner_id: number;
      /** Is Archived */
      is_archived: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ProjectListItem */
    ProjectListItem: {
      /** Id */
      id: number;
      /** Key */
      key: string;
      /** Name */
      name: string;
      role: components['schemas']['ProjectRole'];
      /** Is Archived */
      is_archived: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ProjectPatch */
    ProjectPatch: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
    };
    /** ProjectRead */
    ProjectRead: {
      /** Id */
      id: number;
      /** Key */
      key: string;
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      owner: components['schemas']['UserBrief'];
      /** Members Count */
      members_count: number;
      /** Tasks Count */
      tasks_count: number;
      /** Is Archived */
      is_archived: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * ProjectRole
     * @description Project membership role with hierarchy used by permission checks.
     * @enum {string}
     */
    ProjectRole: 'owner' | 'admin' | 'member' | 'viewer';
    /**
     * Role
     * @enum {string}
     */
    Role: 'user' | 'admin';
    /** TaskAssign */
    TaskAssign: {
      /** User Id */
      user_id: number;
    };
    /** TaskAssignRead */
    TaskAssignRead: {
      /** Id */
      id: number;
      /** Key */
      key: string;
      assignee?: components['schemas']['UserBrief'] | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** TaskCreate */
    TaskCreate: {
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      /** Assignee Id */
      assignee_id?: number | null;
      /** Status Id */
      status_id?: number | null;
      /** @default MEDIUM */
      priority: components['schemas']['Priority'];
      /** Due Date */
      due_date?: string | null;
      /** Estimated Hours */
      estimated_hours?: number | string | null;
      /** Parent Task Id */
      parent_task_id?: number | null;
    };
    /** TaskListItem */
    TaskListItem: {
      /** Id */
      id: number;
      /** Key */
      key: string;
      /** Title */
      title: string;
      status: components['schemas']['TaskStatusBrief'];
      priority: components['schemas']['Priority'];
      assignee?: components['schemas']['UserBrief'] | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** TaskPatch */
    TaskPatch: {
      /** Title */
      title?: string | null;
      /** Description */
      description?: string | null;
      priority?: components['schemas']['Priority'] | null;
      /** Due Date */
      due_date?: string | null;
      /** Estimated Hours */
      estimated_hours?: number | string | null;
      /** Parent Task Id */
      parent_task_id?: number | null;
    };
    /** TaskPositionRead */
    TaskPositionRead: {
      /** Id */
      id: number;
      /** Key */
      key: string;
      status: components['schemas']['TaskStatusBrief'];
      /** Rank */
      rank: number;
      /** Version */
      version: number;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** TaskRead */
    TaskRead: {
      /** Id */
      id: number;
      /** Key */
      key: string;
      /** Project Id */
      project_id: number;
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      status: components['schemas']['TaskStatusBrief'];
      priority: components['schemas']['Priority'];
      creator: components['schemas']['UserBrief'];
      assignee?: components['schemas']['UserBrief'] | null;
      /** Labels */
      labels?: components['schemas']['LabelRead'][];
      /**
       * Comments Count
       * @default 0
       */
      comments_count: number;
      /**
       * Watchers Count
       * @default 0
       */
      watchers_count: number;
      /** Parent Task Id */
      parent_task_id?: number | null;
      /** Due Date */
      due_date?: string | null;
      /** Estimated Hours */
      estimated_hours?: string | null;
      /** Version */
      version: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** TaskReorder */
    TaskReorder: {
      /** Status Id */
      status_id: number;
      /** Before Task Id */
      before_task_id?: number | null;
      /** After Task Id */
      after_task_id?: number | null;
    };
    /** TaskStatusBrief */
    TaskStatusBrief: {
      /** Id */
      id: number;
      /** Key */
      key: string;
      /** Name */
      name: string;
    };
    /** TaskStatusCreate */
    TaskStatusCreate: {
      /** Name */
      name: string;
      /** Key */
      key: string;
      /** Color */
      color: string;
      /** Position */
      position?: number | null;
    };
    /** TaskStatusPatch */
    TaskStatusPatch: {
      /** Name */
      name?: string | null;
      /** Color */
      color?: string | null;
      /** Position */
      position?: number | null;
    };
    /** TaskStatusRead */
    TaskStatusRead: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Key */
      key: string;
      /** Color */
      color: string;
      /** Position */
      position: number;
    };
    /** TaskTransition */
    TaskTransition: {
      /** Status Id */
      status_id: number;
    };
    /** TaskTransitionRead */
    TaskTransitionRead: {
      /** Id */
      id: number;
      /** Key */
      key: string;
      status: components['schemas']['TaskStatusBrief'];
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** Token */
    Token: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
    };
    /** UserBrief */
    UserBrief: {
      /** Id */
      id: number;
      /** Username */
      username: string;
    };
    /** UserRead */
    UserRead: {
      /** Username */
      username: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Id */
      id: number;
      /** Is Active */
      is_active: boolean;
      role: components['schemas']['Role'];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** UserRegister */
    UserRegister: {
      /** Username */
      username: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /**
       * Password
       * Format: password
       */
      password: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** WatcherRead */
    WatcherRead: {
      user: components['schemas']['UserBrief'];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  liveness_probe_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  readiness_probe_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  register_api_v1_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserRegister'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  login_api_v1_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/x-www-form-urlencoded': components['schemas']['Body_login_api_v1_login_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Token'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  refresh_api_v1_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Token'];
        };
      };
    };
  };
  logout_api_v1_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  about_api_v1_about_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'];
        };
      };
    };
  };
  list_projects_api_v1_projects_get: {
    parameters: {
      query?: {
        search?: string | null;
        archived?: boolean | null;
        sort?: string | null;
        page?: number;
        page_size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Paginated_ProjectListItem_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_project_api_v1_projects_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjectCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectCreated'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_project_api_v1_projects__project_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_project_api_v1_projects__project_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjectPatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  archive_project_api_v1_projects__project_id__archive_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  restore_project_api_v1_projects__project_id__restore_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  transfer_ownership_api_v1_projects__project_id__transfer_ownership_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OwnershipTransfer'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_members_api_v1_projects__project_id__members_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MemberList'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  add_member_api_v1_projects__project_id__members_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MemberAdd'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MemberRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_member_api_v1_projects__project_id__members__user_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  change_member_role_api_v1_projects__project_id__members__user_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
        user_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MemberRolePatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MemberRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_statuses_api_v1_projects__project_id__statuses_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskStatusRead'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_status_api_v1_projects__project_id__statuses_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TaskStatusCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskStatusRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_status_api_v1_projects__project_id__statuses__status_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
        status_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_status_api_v1_projects__project_id__statuses__status_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
        status_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TaskStatusPatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskStatusRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_tasks_api_v1_projects__project_id__tasks_get: {
    parameters: {
      query?: {
        search?: string | null;
        status?: string | null;
        priority?: components['schemas']['Priority'] | null;
        assignee_id?: number | null;
        creator_id?: number | null;
        due_before?: string | null;
        due_after?: string | null;
        sort?: string | null;
        page?: number;
        page_size?: number;
      };
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Paginated_TaskListItem_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_task_api_v1_projects__project_id__tasks_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TaskCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_board_api_v1_projects__project_id__board_get: {
    parameters: {
      query?: {
        limit_per_column?: number;
      };
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BoardRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_task_api_v1_tasks__task_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_task_api_v1_tasks__task_id__delete: {
    parameters: {
      query?: never;
      header?: {
        'If-Match'?: string | null;
      };
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_task_api_v1_tasks__task_id__patch: {
    parameters: {
      query?: never;
      header?: {
        'If-Match'?: string | null;
      };
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TaskPatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  transition_task_api_v1_tasks__task_id__transition_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TaskTransition'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskTransitionRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  assign_task_api_v1_tasks__task_id__assign_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TaskAssign'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskAssignRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  unassign_task_api_v1_tasks__task_id__unassign_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskAssignRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reorder_task_api_v1_tasks__task_id__reorder_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TaskReorder'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaskPositionRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_project_activity_api_v1_projects__project_id__activity_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Paginated_ActivityEventRead_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_task_activity_api_v1_tasks__task_id__activity_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
      header?: never;
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Paginated_ActivityEventRead_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  project_events_api_v1_projects__project_id__events_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_comments_api_v1_tasks__task_id__comments_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
      header?: never;
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Paginated_CommentRead_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_comment_api_v1_tasks__task_id__comments_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CommentCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommentRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_comment_api_v1_comments__comment_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        comment_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_comment_api_v1_comments__comment_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        comment_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CommentPatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommentRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_labels_api_v1_projects__project_id__labels_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LabelRead'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_label_api_v1_projects__project_id__labels_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LabelCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LabelRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_label_api_v1_projects__project_id__labels__label_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
        label_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_label_api_v1_projects__project_id__labels__label_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
        label_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LabelPatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LabelRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  attach_label_api_v1_tasks__task_id__labels__label_id__post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
        label_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LabelRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  detach_label_api_v1_tasks__task_id__labels__label_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
        label_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_watchers_api_v1_tasks__task_id__watchers_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WatcherRead'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  watch_task_api_v1_tasks__task_id__watch_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WatcherRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  unwatch_task_api_v1_tasks__task_id__unwatch_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_watcher_api_v1_tasks__task_id__watchers__user_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_notifications_api_v1_notifications_get: {
    parameters: {
      query?: {
        read?: boolean | null;
        page?: number;
        page_size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Paginated_NotificationRead_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  mark_notification_read_api_v1_notifications__notification_id__read_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        notification_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotificationRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  mark_all_notifications_read_api_v1_notifications_read_all_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
