apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: nexadesk
  labels:
    app.kubernetes.io/name: nexadesk
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nexadesk
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nexadesk
        app.kubernetes.io/component: frontend
    spec:

      containers:
        - name: frontend
          image: nexadesk-frontend:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          env:
            - name: API_UPSTREAM
              value: backend:8000
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
