apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: nexadesk
  labels:
    app.kubernetes.io/name: nexadesk
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # PostgreSQL
  POSTGRES_PASSWORD: "nexadesk_local_pass"
  DATABASE_URL: "postgresql+asyncpg://nexadesk:nexadesk_local_pass@db:5432/nexadesk"

  # JWT
  ACCESS_SECRET: "bf671c2d952ef05e4792FAKEFAKEFAKEFAKEFAKEc84c2fa443bcc637f0b9494d"
  REFRESH_SECRET: "bf671c2d952ef05e4792FAKEFAKEFAKEFAKEFAKEc84c2fa443bcc637f0b9494d"
